config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'admin/list'

  get 'admin/move'

  get 'admin/moveback'

  delete 'admin/deletestudent'

  delete 'admin/deleteworkshop'

  delete 'admin/deleteworkstudent'

  get 'admin/geditworkshop'

  get 'admin/geditworkstudent'

  put 'admin/editworkshop'

  put 'admin/editworkstudent'

  get 'admin/workshops'

  post 'admin/addworkshop'
  
  get 'admin/students'

  post 'admin/addstudent'

  get 'admin/workstudentslist'

  get 'students/attendance'

  get 'students/attendances'

  post 'students/studentworkshops'

  get 'students/applicationfinished'

  get 'students/search'

  get 'admin/spage'

  get 'admin/search'
  
  resources :students
  root to: 'students#new'

  devise_for :admins, path_names: {
    sign_up: ''
  }

end

app/views/admin/addworkshop.js.erb
$("<tr>
    <td><%= @workshop.year %></td>
    <td><%= @workshop.semester %></td>
    <td><%= @workshop.name %></td>
</tr></br>").appendTo("#workshops");

app/views/admin/deletestudent.html.erb
<h2>Deleted student</h2>

app/views/admin/deleteworkshop.html.erb
<h2>Workshop deleted</h2>

app/views/admin/editstudents.html.erb
<div class="container">
<h2>Add students</h2>
<tr>
	<td><%= @ws.name %></td>
	<td><%= @ws.year %></td>
	<td><%= @ws.semester %></td>
</tr><br>

<% @currentstudents.each do |cs| %>
<tr>
	<td><%= cs.unmid %></td>
  <td><%= cs.name %></td>
  <td><%= cs.email %></td>
</tr><br>
<% end %>

<div class="field form-group col-md-3">
<%= form_tag('/admin/addstudent', multipart: true, method: :post) do %>
    <div class="row">
      <p><strong>UNM ID</strong></p>
      <%= number_field_tag :unmid, nil, :required => true, in: 100000000...200000001, :onkeypress => "return isNumeric(event)", :oninput => "maxLengthCheck(this)", :class => "form-control" %>
    </div>
    <div class="row">
      <p><strong>Name</strong></p>
      <%=  text_field_tag :name, nil, :required => true , class: "form-control" %>
    </div>
        <div class="row">
      <p><strong>Email</strong></p>
      <%=  text_field_tag :email, nil, :required => true , class: "form-control" %>
    </div>
<%= hidden_field_tag 'workshop_id', @ws.id %>
  <br>
  <div class="row">
  <div class="col-md-5 actions">
    <%= submit_tag "Submit", :name => nil, class: "btn btn-success" %>
  </div>
  </div>
<% end %>
</div>
</div>

<script>
(function(window, location) {
  history.replaceState(null, document.title, location.pathname+"#!/history");
  history.pushState(null, document.title, location.pathname);

  window.addEventListener("popstate", function() {
    if(location.hash === "#!/history") {
    history.replaceState(null, document.title, location.pathname);
    setTimeout(function(){
      location.replace("<%= admin_workshops_path %>");
    },0);
    }
  }, false);
}(window, location));
</script>
<script>
  function maxLengthCheck(object) {
    if (object.value.length > object.max.length)
      object.value = object.value.slice(0, object.max.length)
  }
    
  function isNumeric (evt) {
    var theEvent = evt || window.event;
    var key = theEvent.keyCode || theEvent.which;
    key = String.fromCharCode (key);
    var regex = /[0-9]|\./;
    if ( !regex.test(key) ) {
      theEvent.returnValue = false;
      if(theEvent.preventDefault) theEvent.preventDefault();
    }
  }
</script>

app/views/admin/editworkshop.html.erb
<p>Workshop edited</p>

app/views/admin/editworkstudent.html.erb
<h1>Work Student edited</h1>

app/views/admin/geditworkshop.html.erb
<h2>Edit workshop</h2>
<%= form_tag('/admin/editworkshop', multipart: true, method: :put) do %>

<%= select_tag "year", options_for_select( 2015.. DateTime.now.year, @workshop.year) %>
<%= select_tag "semester", options_for_select( @sems , @workshop.semester) %>
<%= text_field_tag :name, @workshop.name %>
<%= hidden_field_tag :id , @workshop.id %>
<%= submit_tag "Submit" %>
<% end %>

app/views/admin/geditworkstudent.html.erb
<h2>Edit student</h2>

<div class="field form-group col-md-3">
<%= form_tag('/admin/editworkstudent', multipart: true, method: :put) do %>
    <div class="row">
      <p><strong>UNM ID</strong></p>
      <%= number_field_tag :unmid, value = @workstudent.unmid, :required => true, in: 100000000...200000001, :onkeypress => "return isNumeric(event)", :oninput => "maxLengthCheck(this)", :class => "form-control" %>
    </div>
    <div class="row">
      <p><strong>Name</strong></p>
      <%=  text_field_tag :name, value = @workstudent.name, :required => true , class: "form-control" %>
    </div>
        <div class="row">
      <p><strong>Email</strong></p>
      <%=  text_field_tag :email, value = @workstudent.email, :required => true , type: "email", class: "form-control" %>
    </div>
    <%= hidden_field_tag :id , @workstudent.id %>
    <%= hidden_field_tag :wsid , @worksid %>
  <br>
  <div class="row">
  <div class="col-md-5 actions">
    <%= submit_tag "Submit", :name => nil, class: "btn btn-success" %>
  </div>
  </div>
<% end %>
</div>

app/views/admin/index.html.erb
<div class="section">
    <div class="container cont">
        <div class="row">
            <div class="col-sm-12">
            <h3>Waiting list</h3>
                <% if @pendingstudents.size == 0 %>
                <p>There are no students in the waiting list</p>
                <% else %>
                <table class="table table-bordered table-hover table-condensed">
                <thead>
                  <tr>
                    <th>UNM ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Info</th>
                  </tr>
                </thead>
                <% @pendingstudents.each do |s| %>
                <tr>
                    <td><%= s.unmid %></td>
                    <td><%= s.name %></td>
                    <td><%= s.email %></td>
                    <% if WorkshopsStudent.select(:workshop_id).where(:unmid => s.unmid).size >= 4 %>
                    <td><%= link_to "Move to issued section" , admin_move_path(:id => s.id) , class: "btn btn-default btn-success", data: { confirm: "Are you sure?" }%></td>
                    <% else %>
                    <td>This student didnt attend at least 4 workshops</td>
                    <% end %>
                    <td><%= link_to "Delete" , admin_deletestudent_path(:id => s.id) ,:method => :delete, class: "btn btn-default btn-danger", data: { confirm: "Are you sure?" }%></td>
                </tr>
                <% end %>
                </table>
                <% end %>
            </div>
        </div>
    </div>
</div>
<script>
(function(window, location) {
  history.replaceState(null, document.title, location.pathname+"#!/history");
  history.pushState(null, document.title, location.pathname);

  window.addEventListener("popstate", function() {
    if(location.hash === "#!/history") {
    history.replaceState(null, document.title, location.pathname);
    setTimeout(function(){
      location.replace("<%= admin_index_path %>");
    },0);
    }
  }, false);
}(window, location));
</script>

app/views/admin/moveback.html.erb
<h2>Moved back</h2>

app/views/admin/spage.html.erb
<div class="section">
<div class="container" id="cont1">
<div class="col-xs-12">
	<div class="row">
		<div class="col-xs-12">
		<h3 class="text-primary">Please enter UNM ID to check for the details of a person:</h3>
		</div>
		<%= form_tag('/admin/search', :method => 'get') do %>
		<div class="col-xs-6">
		<%= number_field_tag :unmid, params[:unmid], :required => true, in: 100000000...200000001, :onkeypress => "return isNumeric(event)", :oninput => "maxLengthCheck(this)", class: "form-control" %>
		</div>
		<%= submit_tag "Search", :name => nil, class: "btn btn-success" %>
		<% end %>
	</div>
</div>
</div>
</div>
<script>
  function maxLengthCheck(object) {
    if (object.value.length > object.max.length)
      object.value = object.value.slice(0, object.max.length)
  }
    
  function isNumeric (evt) {
    var theEvent = evt || window.event;
    var key = theEvent.keyCode || theEvent.which;
    key = String.fromCharCode (key);
    var regex = /[0-9]|\./;
    if ( !regex.test(key) ) {
      theEvent.returnValue = false;
      if(theEvent.preventDefault) theEvent.preventDefault();
    }
  }
</script>

app/views/admin/students.html.erb
<h2>Students</h2>

<div id="students">
<% @students.each do |s| %>
<tr>
    <td><%= Workshop.find_by(id: s.workshop_id).name %></td>
    <td><%= Workshop.find_by(id: s.workshop_id).year %></td>
	<td><%= Workshop.find_by(id: s.workshop_id).semester %></td>
    <td><%= s.unmid %></td>
</tr></br>
<% end %>
</div>

app/views/admin/workshops.html.erb
<div class="container">

<h2>New workshop</h2>

<%= form_tag('/admin/addworkshop', multipart: true, method: :post) do %>

<div class="field form-group col-sm-2">
<%= select_tag "year", options_for_select( 2015.. DateTime.now.year ),:class => 'form-control' %>
</div>
<div class="field form-group col-sm-2">
<%= select_tag "semester", "<option>Fall</option><option>Summer</option><option>Spring</option>".html_safe, :class => 'form-control'%>
</div>
<div class="field form-group col-sm-5">
<%= text_field_tag :name,nil,:required => true, :class => 'form-control' %>
</div>
<div class="field form-group col-sm-3"><br>
<%= submit_tag "Submit", :class => 'btn btn-success'%>
</div>
<% end %>

<br><br>
<h2>Workshops</h2>
<div id="workshops">
    <% if @workshops.size == 0 %>
    <h4 class="text-primary">There are no workshops. Add one from the form above</h4>
    <% else %>
  <table class="table table-bordered table-hover table-condensed">
    <thead>
        <tr>
          <th>Name</th>
          <th>Semester</th>
          <th>Year</th>
          <th>List</th>
          <th>Delete</th>
          <th>Edit workshop</th>
        </tr>
    </thead>
	<% @workshops.each do |w| %>
	<tr>
	    <td><%= w.name %></td>
      <td><%= w.semester %></td>
      <td><%= w.year %></td>
	    <td><%= link_to 'List students', admin_workstudentslist_path(:id => w.id ), class: "btn btn-default btn-success" %></td>
	    <td><%= link_to 'Delete Workshop', admin_deleteworkshop_path(:id => w.id ),:method => :delete, class: "btn btn-default btn-danger",data: { confirm: "Are you sure you want to delete this workshop?" } %></td>
	    <td><%= link_to 'Edit Workshop', admin_geditworkshop_path(:id => w.id ),:method => :get, class: "btn btn-default" ,data: { confirm: "Are you sure you want to edit this workshop?" }%></td>
	</tr>
	<% end %>
	<% end %>
</div>

</div>

<script>
(function(window, location) {
  history.replaceState(null, document.title, location.pathname+"#!/history");
  history.pushState(null, document.title, location.pathname);

  window.addEventListener("popstate", function() {
    if(location.hash === "#!/history") {
    history.replaceState(null, document.title, location.pathname);
    setTimeout(function(){
      location.replace("<%= admin_index_path %>");
    },0);
    }
  }, false);
}(window, location));
</script>

app/views/admin/workstudentslist.html.erb
<div class="container">
<h4>Add a student to this workshop</h4>
<% if flash[:error] %>
<h4 class="text-danger"><%= flash[:error] %></h4>
<% end %>
<div class="row">
<%= form_tag('/admin/addstudent', multipart: true, method: :post) do %>
    <div class="field form-group col-sm-3">
      <p><strong>Name</strong></p>
      <%=  text_field_tag :name, nil, :required => true , class: "form-control" %>
    </div>
    <div class="field form-group col-sm-3">
      <p><strong>UNM ID</strong></p>
      <%= number_field_tag :unmid, nil, :required => true, in: 100000000...200000001, :onkeypress => "return isNumeric(event)", :oninput => "maxLengthCheck(this)", :class => "form-control" %>
    </div>
    <div class="field form-group col-sm-3">
      <p><strong>Email</strong></p>
      <%=  text_field_tag :email, nil, :required => true , type: "email", class: "form-control" %>
    </div>
    <%= hidden_field_tag 'workshop_id', @ws.id %>
  <br>
  <div class="col-sm-3 actions">
    <%= submit_tag "Submit", :name => nil, class: "btn btn-success", :style => "margin-top: 10px;"  %>
  </div>
<% end %>
</div>

<table class="table table-bordered table-hover table-condensed">
    <thead>
        <tr>
          <th>Workshop Name</th>
          <th>Year</th>
          <th>Semester</th>
        </tr>
      </thead>
<tr>
  <td><%= @ws.name %></td>
  <td><%= @ws.year %></td>
  <td><%= @ws.semester %></td>
</tr>
</table>

<h4>Students</h4>
<% if @currentstudents.size == 0 %>
<p>There are no students in this workshop. You can add the students by using the form below</p>
<% else %>
<table class="table table-bordered table-hover table-condensed">
    <thead>
        <tr>
          <th>UNM ID</th>
          <th>Name</th>
          <th>Email</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
      </thead>
<% @currentstudents.each do |cs| %>
      <tr>
        <td><%= cs.unmid %></td>
        <td><%= cs.name %></td>
        <td><%= cs.email %></td>
        <td><%= link_to 'Edit Student', admin_geditworkstudent_path(:id => cs.id, :wsid => @ws.id ),:method => :get, class: "btn btn-default" ,data: { confirm: "Are you sure you want to edit this student?" }%></td>
        <td><%= link_to 'Delete Student', admin_deleteworkstudent_path(:id => cs.id, :wsid => @ws.id ),:method => :delete, class: "btn btn-default",data: { confirm: "Are you sure you want to delete this student?" } %></td>
      </tr>
<% end %>
</table>
<% end %>
</div>

<script>
(function(window, location) {
  history.replaceState(null, document.title, location.pathname+"#!/history");
  history.pushState(null, document.title, location.pathname);

  window.addEventListener("popstate", function() {
    if(location.hash === "#!/history") {
    history.replaceState(null, document.title, location.pathname);
    setTimeout(function(){
      location.replace("<%= admin_workshops_path %>");
    },0);
    }
  }, false);
}(window, location));
</script>
<script>
  function maxLengthCheck(object) {
    if (object.value.length > object.max.length)
      object.value = object.value.slice(0, object.max.length)
  }
    
  function isNumeric (evt) {
    var theEvent = evt || window.event;
    var key = theEvent.keyCode || theEvent.which;
    key = String.fromCharCode (key);
    var regex = /[0-9]|\./;
    if ( !regex.test(key) ) {
      theEvent.returnValue = false;
      if(theEvent.preventDefault) theEvent.preventDefault();
    }
  }
</script>