config/routes.rb
Rails.application.routes.draw do
  get 'admin/index'

  get 'admin/list'

  get 'admin/move'

  get 'admin/moveback'

  delete 'admin/deletestudent'

  delete 'admin/deleteworkshop'

  delete 'admin/deleteworkstudent'

  get 'admin/geditworkshop'

  get 'admin/geditworkstudent'

  put 'admin/editworkshop'

  put 'admin/editworkstudent'

  get 'admin/workshops'

  post 'admin/addworkshop'
  
  get 'admin/students'

  post 'admin/addstudent'

  get 'admin/workstudentslist'

  get 'students/attendance'

  get 'students/attendances'

  post 'students/studentworkshops'

  get 'students/applicationfinished'

  get 'students/search'

  get 'admin/spage'

  get 'admin/search'
  
  resources :students
  root to: 'students#new'

  devise_for :admins, path_names: {
    sign_up: ''
  }

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse" style="border-radius:0px">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-3">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <% if admin_signed_in? %>
          <a class="navbar-brand" href="<%= admin_index_path %>">GTA</a>
          <% else %>
          <a class="navbar-brand" href="<%= root_path %>">GTA</a>
          <% end %>
        </div>
    
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbar-collapse-3">
          <ul class="nav navbar-nav navbar-right">
          <% if admin_signed_in? %>
            <li><%= link_to('Search for a student', admin_spage_path)%></li>
            <li><%= link_to('Waiting List', admin_index_path)%></li>
            <li><%= link_to('Issued List', admin_list_path)%></li>
            <li><%= link_to('Workshops', admin_workshops_path)%></li>
            <li><%= link_to('Logout', destroy_admin_session_path, :method => :delete) %></li>
          <% else %>
            <li><%= link_to('Home', root_path)%></li>
            <li><%= link_to('Admin Login', admin_session_path)%></li>
          <% end %>
          </ul>
          <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-collapse3">
            <form class="navbar-form navbar-right" role="search">
              <div class="form-group">
                <input type="text" class="form-control" placeholder="Search" />
              </div>
              <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
            </form>
          </div>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container -->
    </nav><!-- /.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render partial: 'layouts/header' %>
<%= yield %>
</body>
</html>